if (NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE Release)
endif()
message(STATUS "runtime Build Type: ${CMAKE_BUILD_TYPE}")
if(CONAN_SETTINGS_ARCH MATCHES "x86_64")
    if (CMAKE_BUILD_TYPE MATCHES "Release|release")
        set(CMAKE_C_FLAGS "-fPIC -Wall -Wno-reorder")
        set(CMAKE_CXX_FLAGS "-fPIC -Wall -Wno-reorder")
    else()
        set(BUILD_UNITTEST ON)     
        set(CMAKE_CXX_FLAGS " -g -O0 --coverage -fprofile-arcs -ftest-coverage -Wno-reorder")
        set(CMAKE_C_FLAGS " -g -O0 --coverage -fprofile-arcs -ftest-coverage -Wno-reorder")
    endif()
else()
    if (CMAKE_BUILD_TYPE MATCHES "Release|release")
        set(CMAKE_C_FLAGS "-fPIC -Wall -Wno-reorder")
        set(CMAKE_CXX_FLAGS "-fPIC -Wall -Wno-reorder")
    else()
        set(BUILD_UNITTEST ON)
        set(CMAKE_CXX_FLAGS " -g -O0 -Wno-error=cpp")
        set(CMAKE_C_FLAGS " -g -O0 -Wno-error=cpp")
    endif()
endif()

message(STATUS "runtime SLOG_SHOW: ${SLOG_SHOW_LEVEL}")
set(CMAKE_C_STANDARD 99)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED True)

if(CMAKE_INSTALL_PREFIX STREQUAL "/usr/local")
    set(CMAKE_INSTALL_PREFIX ${PROJECT_BINARY_DIR}/install)
endif()
message(STATUS "runtime Install Directory:" ${CMAKE_INSTALL_PREFIX})

